INFO:root:Executed R('load(\'../../instructor/assignments/hw6/hw6-test.rda\')')
INFO:root:Executed R('init1 <- bml.init(2000, 1000, 0.4)')
INFO:root:(1 points) R('all.equal(dim(init1), c(2000, 1000))')[0] is True
INFO:root:(1 points) R('all.equal(sum(init1 == 1)/2000000, 0.2, tolerance = 0.02)')[0] is True
INFO:root:(1 points) R('all.equal(sum(init1 == 2)/2000000, 0.2, tolerance = 0.02)')[0] is True
INFO:root:Executed R('mat.idx <- which(sapply(bml.step(test$m1), is.matrix))')
INFO:root:Executed R('log.idx <- which(!sapply(bml.step(test$m1), is.matrix))')
INFO:root:Executed R('m1 <- all.equal(bml.step(test$m1)[[mat.idx]], sol$m1[[1]])')[0]
INFO:root:Executed R('m1.swap <- all.equal(swap(bml.step(test$m1)[[mat.idx]]), sol$m1.swap[[1]])')[0]
INFO:root:(1 points) R('m1==T | m1.swap==T')[0] is True
INFO:root:Executed R('m2 <- all.equal(bml.step(test$m2)[[mat.idx]], sol$m2[[1]])')[0]
INFO:root:Executed R('m2.swap <- all.equal(swap(bml.step(test$m2)[[mat.idx]]), sol$m2.swap[[1]])')[0]
INFO:root:(1 points) R('m2==T | m2.swap==T')[0] is True
INFO:root:Executed R('m3 <- all.equal(bml.step(test$m3)[[mat.idx]], sol$m3[[1]])')[0]
INFO:root:Executed R('m3.swap <- all.equal(swap(bml.step(test$m3)[[mat.idx]]), sol$m3.swap[[1]])')[0]
INFO:root:(1 points) R('m3==T | m3.swap==T')[0] is True
INFO:root:Executed R('m4 <- all.equal(bml.step(test$m4)[[mat.idx]], sol$m4[[1]])')[0]
ERROR:root:Got exception on main handler
Traceback (most recent call last):
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/gradebook/score.py", line 164, in run
    exec(command, g)
  File "<string>", line 1, in <module>
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 246, in __call__
    res = self.eval(p)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in if (space == 0) return(TRUE) else return(FALSE) : 
  argument is of length zero

ERROR:root:Traceback (most recent call last):
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/gradebook/score.py", line 164, in run
    exec(command, g)
  File "<string>", line 1, in <module>
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 246, in __call__
    res = self.eval(p)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in if (space == 0) return(TRUE) else return(FALSE) : 
  argument is of length zero

Traceback (most recent call last):
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/gradebook/score.py", line 164, in run
    exec(command, g)
  File "<string>", line 1, in <module>
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 246, in __call__
    res = self.eval(p)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in if (space == 0) return(TRUE) else return(FALSE) : 
  argument is of length zero

INFO:root:Executed R('m4.swap <- all.equal(swap(bml.step(test$m4)[[mat.idx]]), sol$m4.swap[[1]])')[0]
ERROR:root:Got exception on main handler
Traceback (most recent call last):
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/gradebook/score.py", line 164, in run
    exec(command, g)
  File "<string>", line 1, in <module>
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 246, in __call__
    res = self.eval(p)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in if (space == 0) return(TRUE) else return(FALSE) : 
  argument is of length zero

ERROR:root:Traceback (most recent call last):
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/gradebook/score.py", line 164, in run
    exec(command, g)
  File "<string>", line 1, in <module>
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 246, in __call__
    res = self.eval(p)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in if (space == 0) return(TRUE) else return(FALSE) : 
  argument is of length zero

Traceback (most recent call last):
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/gradebook/score.py", line 164, in run
    exec(command, g)
  File "<string>", line 1, in <module>
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 246, in __call__
    res = self.eval(p)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in if (space == 0) return(TRUE) else return(FALSE) : 
  argument is of length zero

ERROR:root:(1 points) Checking R('m4==T | m4.swap==T')[0]
ERROR:root:... Expecting: True
ERROR:root:... But got:   Traceback error
ERROR:root:Got exception:
Traceback (most recent call last):
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 246, in __call__
    res = self.eval(p)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in eval(expr, envir, enclos) : object 'm4' not found

ERROR:root:Traceback (most recent call last):
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 246, in __call__
    res = self.eval(p)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in eval(expr, envir, enclos) : object 'm4' not found

Traceback (most recent call last):
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 246, in __call__
    res = self.eval(p)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in eval(expr, envir, enclos) : object 'm4' not found

INFO:root:Executed R('m5 <- all.equal(bml.step(test$m5)[[mat.idx]], sol$m5[[1]])')[0]
INFO:root:Executed R('m5.swap <- all.equal(swap(bml.step(test$m5)[[mat.idx]]), sol$m5.swap[[1]])')[0]
INFO:root:(1 points) R('m5==T | m5.swap==T')[0] is True
ERROR:root:(1 points) Checking R('all.equal(bml.step(test$m6)[[mat.idx]], sol$m6[[1]])')[0]
ERROR:root:... Expecting: True
ERROR:root:... But got:   Traceback error
ERROR:root:Got exception:
Traceback (most recent call last):
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 246, in __call__
    res = self.eval(p)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in grid.old[row_index, col_index + 1] : subscript out of bounds

ERROR:root:Traceback (most recent call last):
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 246, in __call__
    res = self.eval(p)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in grid.old[row_index, col_index + 1] : subscript out of bounds

Traceback (most recent call last):
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 246, in __call__
    res = self.eval(p)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in grid.old[row_index, col_index + 1] : subscript out of bounds

INFO:root:Executed R('m7 <- all.equal(bml.step(test$m7)[[mat.idx]], sol$m7[[1]])')[0]
INFO:root:Executed R('m7.swap <- all.equal(swap(bml.step(test$m7)[[mat.idx]]), sol$m7.swap[[1]])')[0]
INFO:root:(1 points) R('m7==T | m7.swap==T')[0] is True
INFO:root:Executed R('m8 <- all.equal(bml.step(test$m8)[[mat.idx]], sol$m8[[1]])')[0]
INFO:root:Executed R('m8.swap <- all.equal(swap(bml.step(test$m8)[[mat.idx]]), sol$m8.swap[[1]])')[0]
INFO:root:(1 points) R('m8==T | m8.swap==T')[0] is True
INFO:root:Executed R('m9 <- all.equal(bml.step(test$m9)[[mat.idx]], sol$m9[[1]])')[0]
INFO:root:Executed R('m9.swap <- all.equal(swap(bml.step(test$m9)[[mat.idx]]), sol$m9.swap[[1]])')[0]
INFO:root:(1 points) R('m9==T | m9.swap==T')[0] is True
INFO:root:Executed R('m10 <- all.equal(bml.step(test$m10)[[mat.idx]], sol$m10[[1]])')[0]
INFO:root:Executed R('m10.swap <- all.equal(swap(bml.step(test$m10)[[mat.idx]]), sol$m10.swap[[1]])')[0]
INFO:root:(1 points) R('m10==T | m10.swap==T')[0] is True
INFO:root:(1 points) R('all.equal(bml.step(test$m10)[[log.idx]], sol$m10[[2]])')[0] is True
ERROR:root:(1 points) Checking R('all.equal(bml.step(test$m6)[[log.idx]], sol$m6[[2]])')[0]
ERROR:root:... Expecting: True
ERROR:root:... But got:   Traceback error
ERROR:root:Got exception:
Traceback (most recent call last):
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 246, in __call__
    res = self.eval(p)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in grid.old[row_index, col_index + 1] : subscript out of bounds

ERROR:root:Traceback (most recent call last):
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 246, in __call__
    res = self.eval(p)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in grid.old[row_index, col_index + 1] : subscript out of bounds

Traceback (most recent call last):
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 246, in __call__
    res = self.eval(p)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in grid.old[row_index, col_index + 1] : subscript out of bounds

INFO:root:You got a 17 out of 20.
