INFO:root:Executed R('load(\'../../instructor/assignments/quiz3/quiz3-tests.rda\')')
INFO:root:(1 points) R('all.equal(numAtElements(test$test1), sol$test1, check.attributes=F)')[0] is True
INFO:root:(1 points) R('all.equal(numAtElements(test$test2), sol$test2, check.attributes=F)')[0] is True
INFO:root:(1 points) R('all.equal(numAtElements(test$test3), sol$test3, check.attributes=F)')[0] is True
INFO:root:(1 points) R('all.equal(unexclaim(test$test4), sol$test4, check.attributes=F)')[0] is True
INFO:root:(1 points) R('all.equal(unexclaim(test$test5), sol$test5, check.attributes=F)')[0] is True
INFO:root:(1 points) R('all.equal(unexclaim(test$test6), sol$test6, check.attributes=F)')[0] is True
ERROR:root:(1 points) Checking R('all.equal(updateDate(test$test7[[1]], test$test7[[2]]), sol$test7, check.attributes=F)')[0]
ERROR:root:... Expecting: True
ERROR:root:... But got:   Lengths (2, 1) differ (string compare on first 1)
ERROR:root:(1 points) Checking R('all.equal(updateDate(test$test8[[1]], test$test8[[2]]), sol$test8, check.attributes=F)')[0]
ERROR:root:... Expecting: True
ERROR:root:... But got:   Lengths (3, 2) differ (string compare on first 2)
ERROR:root:(1 points) Checking R('all.equal(updateDate(test$test9[[1]], test$test9[[2]]), sol$test9, check.attributes=F)')[0]
ERROR:root:... Expecting: True
ERROR:root:... But got:   Lengths (4, 2) differ (string compare on first 2)
INFO:root:(1 points) R('all.equal(countcatdog(test$test10), sol$test10, check.attributes=F)')[0] is True
INFO:root:Executed R('temp <- countcatdog(test$test11)')
INFO:root:(1 points) R('all.equal(names(temp), names(sol$test11))')[0] is True
INFO:root:(1 points) R('all.equal(temp, sol$test11, check.attributes = F)')[0] is True
INFO:root:(1 points) R('all.equal(countcatdog(test$test12), sol$test12)')[0] is True
INFO:root:(1 points) R('all.equal(sumDigits(test$test13), 7, check.attributes=F)')[0] is True
ERROR:root:(1 points) Checking R('all.equal(sumDigits(test$test14), 0, check.attributes=F)')[0]
ERROR:root:... Expecting: True
ERROR:root:... But got:   Traceback error
ERROR:root:Got exception:
Traceback (most recent call last):
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 246, in __call__
    res = self.eval(p)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in sum(sapply(str_extract_all(chvec, "[[:digit:]]"), as.numeric)) : 
  invalid 'type' (list) of argument

ERROR:root:Traceback (most recent call last):
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 246, in __call__
    res = self.eval(p)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in sum(sapply(str_extract_all(chvec, "[[:digit:]]"), as.numeric)) : 
  invalid 'type' (list) of argument

Traceback (most recent call last):
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 246, in __call__
    res = self.eval(p)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in sum(sapply(str_extract_all(chvec, "[[:digit:]]"), as.numeric)) : 
  invalid 'type' (list) of argument

INFO:root:(1 points) R('all.equal(sumDigits(test$test15), 12, check.attributes=F)')[0] is True
INFO:root:(1 points) R('all.equal(dnaTransform(test$test16), sol$test16, check.attributes=F)')[0] is True
ERROR:root:(1 points) Checking R('all.equal(dnaTransform(test$test17), sol$test17, check.attributes=F)')[0]
ERROR:root:... Expecting: True
ERROR:root:... But got:   2 string mismatches
INFO:root:Executed R('temp2 <- dnaTransform(test$test18)')
INFO:root:(1 points) R('all.equal(length(temp2), 2)')[0] is True
ERROR:root:(1 points) Checking R('all.equal(dnaTransform(test$test18), sol$test18, check.attributes=F)')[0]
ERROR:root:... Expecting: True
ERROR:root:... But got:   2 string mismatches
INFO:root:Executed R('temp3 <- dnaTransform(test$test19)')
INFO:root:(1 points) R('all.equal(length(temp3), 2)')[0] is True
INFO:root:(1 points) R('all.equal(dnaTransform(test$test19), sol$test19, check.attributes=F)')[0] is True
INFO:root:You got a 16 out of 22.
